name: Link checking

on:
  workflow_dispatch:

jobs:
  link-check:
    strategy:
      matrix:
        url: [
          "https://docs.stakater.com/saap2/index.html"
        ]
    runs-on: ubuntu-latest
    steps:
      # Don't stop the workflow if there are errors, but continue and send a message
      # The file name of the link check result has to be unique for each job since the jobs run in parallel
      - name: Check links
        id: link_check
        continue-on-error: true
        run: |
          RANDOM_FILE_NAME=${RANDOM}.txt
          echo "RANDOM_FILE_NAME=$RANDOM_FILE_NAME" >> "$GITHUB_OUTPUT"
          docker run --rm -u $(id -u):$(id -g) -v "$PWD":/mnt ghcr.io/linkchecker/linkchecker:8ae3783 -r 1 --check-extern -F text/$RANDOM_FILE_NAME ${{ matrix.url }}
      - if: ${{ steps.link_check.outcome == 'failure' }}
        name: Create message
        id: message
        run: |
          MESSAGE=":x: Broken links found:\n\n$(cat ${{ steps.link_check.outputs.RANDOM_FILE_NAME }})\n\nFor more details, check the <https://github.com/stakater-ab/handbook/actions/runs/${{ github.run_id }}|GitHub Actions Workflow>"
          MESSAGE="${MESSAGE//'%'/'%25'}"
          MESSAGE="${MESSAGE//$'\n'/'%0A'}"
          MESSAGE="${MESSAGE//$'\r'/'%0D'}"
          echo "MESSAGE<<EOF" >> "$GITHUB_OUTPUT"
          echo "$MESSAGE" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - if: ${{ steps.link_check.outcome == 'failure' }}
        name: Send broken link check result to Slack
        run: |
          echo "${{ steps.message.outputs.MESSAGE }}"
